Repository AY2425S2-CS2103T-T15-2/tp, pull requests merged in 2025-03, with the labels that each got.

#8 Add Sreelakshmi's personal photo
  docs/images/sreelakshmiharidos.png
Labels: priority.High

#10 Add personal Photo
  docs/images/heyitssakinah.png
Labels: type.Task

#15 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#17 edit about us section
  docs/AboutUs.md
Labels: type.Task

#19 Update AboutUS
  docs/AboutUs.md
Labels: type.Task

#29 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#30 add nfr, glossary to DG
  docs/DeveloperGuide.md
Labels: type.Task

#38 Add multiple index deletion in delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement

#37 Update exit
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Low

#55 Add remark command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#59 fix error message
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug

#62 Update user guide for mvp
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Task

#86 Update user guide with group command
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Enhancement

#88 Update Developer Guide
  docs/diagrams/UiClassDiagram.puml
Labels: type.Enhancement

#89 Update StorageClassDiagram
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task

#90 Update BetterModelClassDiagram
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task
