Repository AY2425S2-CS2103T-T15-2/tp, pull requests merged in 2025-04, with the labels that each got.

#116 Fixed bugs on Grade field does not accept a as a valid input
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/model/person/Grade.java
Labels: alpha-bug

#124 All UI bug fixes
  src/main/java/seedu/address/logic/Messages.java
  src/main/resources/view/ColorTheme.css
  src/main/resources/view/CommandGuidePlaceholder.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDisplay.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: alpha-bug

#127 update user guide
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Task

#130 Add new sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/person/SampleDataUtilTest.java
Labels: alpha-bug

#132 Add java docs
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: alpha-bug

#134 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#135 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#136 Update user stories
  docs/DeveloperGuide.md
Labels: type.Task

#198 Duplicate in delete
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/CommandGuidePanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ColorTheme.css
  src/main/resources/view/CommandGuidePlaceholder.fxml
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: alpha-bug

#199 Update UG and output messages
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DisplayCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: type.Bug, type.UG
